Implement parsing Racket-style #%-prefixed symbols
rotty/lexpr-rs pull request #90
Opened 2023-06-02 20:08 UTC by andrew-pa

Per the Racket [Reader documentation, section 1.3.2](https://docs.racket-lang.org/reference/reader.html), Racket allows symbols prefixed with `#%`, with the prefix included in the symbol. This change adds a new option that allows these symbols to be parsed correctly.

2023-06-13 20:54 UTC, rotty requested changes
Thanks a lot for your contribution! The change looks good, besides a few superficial issues.

Note that I'd prefer squashing any subsequent changes into the same commit instead of adding fixup commits to the PR.

2023-06-13 20:54 UTC, rotty commented on lexpr/src/parse/mod.rs
> +    /// Query if Racket-style #% prefixed symbols are allowed
For consistency, please terminate the doc comment with a period.

2023-06-13 20:54 UTC, rotty commented on lexpr/src/parse/mod.rs
> +    /// Choose to allow Racket-style #% prefixed symbols
For consistency, please terminate the doc comment with a period.

2023-06-13 23:21 UTC, andrew-pa commented
> Thanks a lot for your contribution! The change looks good, besides a few superficial issues.
> 
> Note that I'd prefer squashing any subsequent changes into the same commit instead of adding fixup commits to the PR.

Yes no problem thanks for the great library! I've made the changes you requested. I also added "percent" to the name since that is more accurate and I left that out originally.

2023-06-14 19:45 UTC, rotty approved these changes

2023-06-14 19:48 UTC, merged